---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Breno.
--- DateTime: 11-Jul-22 7:48 PM
---

---How to use:
-- at the top:
-- VFS.Include("gamedata/configs/fontsettings.lua")
-- then:
-- getFont().default => returns fonts/...otf

FontName = "GeogrotesqueCompMedium.otf"
FontPath = "fonts/"..FontName
LuaUIFontPath = "LuaUI/Fonts/"..FontName
SkinFontPath = "LuaUI/Widgets/Skins/Evolved/fonts/"..FontName

function getFont()
	return { name = FontName, default = FontPath, LuaUI = LuaUIFontPath, skin = SkinFontPath }
end

